[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 300
bytecode_hash = "none"
evm_version = "osaka"
fs_permissions = [{ access = "read", path = "test/ticks_exact.json" }]

[profile.default.fmt]
wrap_comments = true

[lint]
exclude_lints = ["asm-keccak256", "unsafe-cheatcode", "incorrect-shift"]
