name: certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      confs: ${{ steps.list.outputs.confs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - id: list
        run: echo "confs=$(ls certora/confs/*.conf | xargs -I{} basename {} .conf | jq -nRc '[inputs]')" >> "$GITHUB_OUTPUT"

  verify:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        conf: ${{ fromJson(needs.matrix.outputs.confs) }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Jq
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58 # v2

      - name: Run Certora Config Linter
        run: |
          file="certora/confs/${{ matrix.conf }}.conf"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(jq < "$file")

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

      - name: Install certora
        run: pip install certora-cli

      - name: Run Certora Specs Linter
        run: |
          file="certora/specs/${{ matrix.conf }}.spec"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(certoraCVLFormatter "$file")

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: nightly-1e342ef7d296a674ea248e95ed12c152f7e00ee6

      - name: Copy solc
        run: |
          forge build
          cp ~/.svm/0.8.34/solc-0.8.34 /usr/local/bin

      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
