name: forge

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: nightly-1e342ef7d296a674ea248e95ed12c152f7e00ee6

      - name: Check formatting
        run: forge fmt src test script certora --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: nightly-1e342ef7d296a674ea248e95ed12c152f7e00ee6

      - name: Run forge lint
        run: forge lint src test script certora --deny notes

  sizes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: nightly-1e342ef7d296a674ea248e95ed12c152f7e00ee6

      - name: Run forge build
        run: forge build --force --sizes

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - token-type: 0
            name: standard
          - token-type: 1
            name: no-revert
          - token-type: 2
            name: usdt
          - token-type: 3
            name: revert-to-zero
          - token-type: 4
            name: no-return
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: nightly-1e342ef7d296a674ea248e95ed12c152f7e00ee6
      - name: Run Forge tests (${{ matrix.name }})
        run: forge test --deny warnings
        env:
          TOKEN_TYPE: ${{ matrix.token-type }}
